### ISSUE TITLE
Support additional languages for syntax highlighting

### ISSUE THREAD

**Issue by daurnimator** [hedgedoc/react-client#1367]
**Which part of the project should be enhanced?**

Syntax highlighting should support more languages

**Is your enhancement request related to a problem? Please describe.**

Code syntax highlighting currently only supports what highlight JS supports out of the box.
Upstream highlight.js doesn't add new languages; so how can I e.g. highlight zig code?
Ref: https://github.com/highlightjs/highlight.js/pull/2441#issuecomment-592952765

**Describe the solution you'd like**

Add ability to configure extra highlighting grammars

**Describe alternatives you've considered**

Add support for alternative syntax highlighting engines

**Comment by mrdrogdrog** [comment]
Interesting request. 

Only a bit problematic. highlight js languages are JavaScript files. We integrate them into the bundled frontend with webpack. We can't load additional not-integrated languages at runtime because that would require the use of `eval` or would require to load code from additional urls.
Both is not very appealing.

Of course you could just fork HedgeDoc, change the code and bundle the whole app yourself. But that is a huge overhead for just one grammar.

The smoothest way imho is to open a pull request here. Feel free to add a package to our package.json that contains the grammar and change hljs.ts. (Can't link the file right now because I'm on the phone.)

**Comment by DerMolly** [comment]
This issues is not really actionable. The path was sketched and it will be closed.
