### ISSUE TITLE
Upgrade To Bootstrap 5

### ISSUE THREAD

**Issue by LabinatorSolutions** [hedgedoc/react-client#1696]
### Which part of the project should be enhanced?

Upgrade To Bootstrap 5.1.3+

### Describe the solution you'd like

The generated HTML file is still using an outdated version of Bootstrap (3.4.1). Upgrading to Bootstrap 5.1.3+ might be a good call unless there are some compatibility issues in doing so.

### Describe alternatives you've considered

Alternatively, in an ideal scenario, you might also consider upgrading to an accessible CSS framework instead of Bootstrap. One of the best would be the USWDS (https://designsystem.digital.gov/).

**Comment by mrdrogdrog** [comment]
One of our goals for HD2 is indeed to increase accessibility.

But we don't know if we can achieve this goal in 2.0 or in 2.x. First we have to figure out some more important technical issues. 
We planned to combine the upgrade of bs with a redesign/relayout attempt of the whole app which is quite hard because our last two designers suddenly have jumped off the project. So it could take some time. Maybe we even have to ship 2.0 with BS4 and implement the new UI later. 🤷

**Comment by LabinatorSolutions** [comment]
> One of our goals for HD2 is indeed to increase accessibility.
> 
> But we don't know if we can achieve this goal in 2.0 or in 2.x. First we have to figure out some more important technical issues. We planned to combine the upgrade of bs with a redesign/relayout attempt of the whole app which is quite hard because our last two designers suddenly have jumped off the project. So it could take some time. Maybe we even have to ship 2.0 with BS4 and implement the new UI later. shrug

Thank you for your reply. I wish your team all the best!

All in all, I love your project! If I get any free time next year, I will contact you to see how to join onboard. At the moment, though, my schedule is totally full.

P.S: You can also consider creating a SaaS based solution like HackerMD. Something like a collaboration tool with a subscription model. Many open-source solutions offer cloud services and tools for companies to support their open source development.

**Comment by DerMolly** [comment]
done
