### ISSUE TITLE
Number of character / number of words

### ISSUE THREAD

**Issue by parisni** [hedgedoc/react-client#718]
hello

intersting information are:
- number of charcacter in the resulting format (html, odm, pdf) 
- number of words in the resulting format

right now the information of number of charracter is about every single markdown markup

**Comment by ErikMichelson** [comment]
For the word-count this library looks quite complete in regard to UTF-8 character word-recognition: https://www.npmjs.com/package/words-count

**Comment by DerMolly** [comment]
The request is concerned with the word and character count in the result. So currently only HTML, because there is no PDF export at this moment. This could be done with the html output, but we would need something that extracts the correct word & character count out of an HTML document.

In the mean time we could add word count via the lib @ErikMichelson suggested to the infos in the status bar below the editor. Between lines and length (aka characters would be a neat place)
![grafik](https://user-images.githubusercontent.com/3978662/97745856-c9c89500-1ae9-11eb-9fa0-7922a43acc80.png)

**Comment by ErikMichelson** [comment]
This has been implemented
